uploads = []
generated = []

[[outputs]]
id = "MRaO_WwHESjId8CAkHxzJ"
uri = "file://VSCODE_SETUP.md"
type = "text"
title = "سِيغْمَا Σ — دليل الإعداد الكامل لـ VS Code"

[[outputs]]
id = "j2325_FuE4PjQNE-WH3CE"
uri = "file://sigma-vscode.tar.gz"
type = "unspecified"
title = "سِيغْمَا Σ — كامل المشروع (38 MB)"

[[outputs]]
id = "lia0QkrztsaweiD2bFlhS"
uri = "file://sigma-vscode.zip"
type = "unspecified"
title = "سِيغْمَا Σ — ZIP مصحح لـ Windows"

[[outputs]]
id = "wVscSMcBH8ed21obY69wp"
uri = "file://sigma-windows.zip"
type = "unspecified"
title = "سِيغْمَا Σ — مضبوط لـ Windows"
